# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='name',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
